[package]
name = "ren3"
version = "0.1.0"
authors = ["Aloxaf <bailong104@gmail.com>"]
edition = "2018"

[dependencies]
regex = "^1.0.5"
clap = {version = "^2.32.0", features = ["yaml"]}
sedregex = {git = "https://gitlab.com/Aloxaf/sedregex"}

[profile.release]
opt-level = 3
lto = true